name: Release Charts

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - "*"
env:
  HELM_VERSION: v3.11.3

jobs:
  release-charts:
    name: Release
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Publish ${{ matrix.chart }}
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_SKIP_EXISTING: true
          charts_dir: publish-charts
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
